name: Node CI

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: '10'

    - name: Run Cypress
      run: |
        npm install
        npm run cypress
      env:
        CI: true

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: [checkbalance.js.mp4, checkStatement.js.mp4, makeTransfer.js.mp4]
        path: /home/runner/work/Stone/Stone/cypress/videos/